version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:

  traefik:
    image: traefik:1.5.4-alpine
    command: --docker
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.frontend.rule=Host:monitor.localhost"
      - "traefik.port=8080"
    networks:
      - "proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/traefik.toml:/traefik.toml"
      - "$PWD/acme.json:/acme.json"
    container_name: traefik

  blog:
    image: wordpress:4.7.5-apache
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD:
    labels:
      - "traefik.backend=blog"
      - "traefik.frontend.rule=Host:blog.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    networks:
      - "internal"
      - "proxy"
    depends_on:
      - "traefik"
      - "mysql"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    labels:
      - "traefik.enable=false"
    networks:
      - "internal"
    depends_on:
      - "traefik"

  adminer:
    image: adminer:4.3.1-standalone
    restart: always
    labels:
      - "traefik.backend=adminer"
      - "traefik.frontend.rule=Host:db-admin.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
    networks:
      - "internal"
      - "proxy"
    depends_on:
      - "traefik"
      - "mysql"